[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Força uso do Node.js 22 (necessário para OpenAI SDK)
  node_version = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

